site_name: EcoDynamics.jl
repo_url: https://github.com/gottacatchenall/EcoDynamics.jl
site_description: Julia package for simulation of population and community dynamics across space
site_author: Michael D. Catchen

theme:
  name: material
  logo: assets/logo.png
  palette:
    scheme: default
    primary: teal
    accent: light blue

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: 'build'

nav:
  - Home: index.md
  - Getting started:
    - Quick Start: getting_started/quick_start.md
    - Package design: getting_started/design.md
  - Examples:
    - Bayesian Inference of community dynamics using Turing.jl: examples/community_inference.md
    - Inference of metapopulation dynamics: examples/metapopulation_inference.md  
    - Custom functional response: examples/custom_functional_response.md
    - Transition from species sorting to neutral dynamics in a metacommunity: examples/neutral_to_niche.md
  - Reference:
    - Population dynamics:
      - Overview: model_index/population/overview.md
    - Metapopulation dynamics:
      - Overview: model_index/metapopulation/overview.md
    - Community dynamics: 
      - Overview: model_index/community/overview.md
    - Metacommunity dynamics:  
      - Overview: model_index/metacommunity/overview.md
  - API:
    - Public: lib/public.md
    - Internal: lib/internal.md