site_name: MetacommunityDynamics.jl
repo_url: https://github.com/gottacatchenall/EcoDynamics.jl
site_description: Library for simulation of metapopulation and metacommunity dynamics
site_author: Michael D. Catchen

theme:
  name: material
  palette:
    scheme: default
    primary: white
    accent: indigo

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - admonition
  - pymdownx.details
  - pymdownx.superfences

docs_dir: 'build'

nav:
  - Home: index.md
  - Getting started:
    - Building a network: getting_started/demonstration.md
    - Type system: getting_started/types.md
  - Species level measures:
    - Specificity: species_level/specificity.md
  - Community level measures:
    - Nestedness: community_level/nestedness.md
  - Random networks:
    - Permutations: random_networks/permutations.md
  - Bibliography: bibliography.md